<script setup>
import { ref } from 'vue';
import { router, useForm } from '@inertiajs/vue3';
import AppLayout from '@/Layouts/AppLayout.vue';
import PageHeader from '@/Components/ui/PageHeader.vue';

const props = defineProps({ title: { type: String, default: 'Lessons Learned' }, lessons: { type: Array, default: () => [] }, projects: { type: Array, default: () => [] } });
const showModal = ref(false);
const editingLesson = ref(null);
const form = useForm({ title: '', category: 'Delivery', impact_level: 'medium', recommendation: '', project_id: '' });
const impactClass = (level) => ({ low: 'bg-success/10 text-success', medium: 'bg-warning/10 text-warning', high: 'bg-danger/10 text-danger' }[level]);
function openCreate() { editingLesson.value = null; form.reset(); form.category = 'Delivery'; form.impact_level = 'medium'; showModal.value = true; }
function openEdit(lesson) { editingLesson.value = lesson; Object.assign(form, { title: lesson.title, category: lesson.category, impact_level: lesson.impact_level, recommendation: lesson.recommendation, project_id: lesson.project_id || '' }); showModal.value = true; }
function submit() { const options = { onSuccess: () => { showModal.value = false; form.reset(); } }; editingLesson.value ? form.put(`/reports/lessons/${editingLesson.value.id}`, options) : form.post('/reports/lessons', options); }
function remove(lesson) { if (confirm(`Delete “${lesson.title}”?`)) router.delete(`/reports/lessons/${lesson.id}`, { preserveScroll: true }); }
</script>

<template><AppLayout :title="title"><PageHeader :title="title" subtitle="Capture insights that make future projects stronger"><template #actions><button class="ti-btn ti-btn-primary" @click="openCreate"><i class="ri-add-line me-1"></i> Record Lesson</button></template></PageHeader>
    <div class="grid grid-cols-1 lg:grid-cols-2 xl:grid-cols-3 gap-4"><article v-for="lesson in lessons" :key="lesson.id" class="box mb-0"><div class="box-body"><div class="flex items-start justify-between gap-3"><span class="badge" :class="impactClass(lesson.impact_level)">{{ lesson.impact_level }} impact</span><div><button class="ti-btn ti-btn-icon ti-btn-soft-primary ti-btn-sm" @click="openEdit(lesson)"><i class="ri-pencil-line"></i></button><button class="ti-btn ti-btn-icon ti-btn-soft-danger ti-btn-sm ms-1" @click="remove(lesson)"><i class="ri-delete-bin-line"></i></button></div></div><p class="text-xs uppercase tracking-wide text-textmuted mt-4 mb-1">{{ lesson.category }} · {{ lesson.project?.name || 'General' }}</p><h5 class="mb-3">{{ lesson.title }}</h5><p class="text-textmuted whitespace-pre-line mb-0">{{ lesson.recommendation }}</p></div></article><div v-if="!lessons.length" class="col-span-full box"><div class="box-body py-16 text-center text-textmuted"><i class="ri-lightbulb-line text-4xl"></i><p class="mt-3 mb-0">No lessons have been recorded yet.</p></div></div></div>
    <div v-if="showModal" class="fixed inset-0 z-[80] flex items-center justify-center bg-black/50 p-4"><div class="box w-full max-w-2xl mb-0"><form @submit.prevent="submit"><div class="box-header flex justify-between"><h6 class="box-title mb-0">{{ editingLesson ? 'Edit Lesson' : 'Record Lesson' }}</h6><button type="button" class="ti-btn ti-btn-icon ti-btn-light ti-btn-sm" @click="showModal = false"><i class="ri-close-line"></i></button></div><div class="box-body space-y-4"><div><label class="form-label">Title</label><input v-model="form.title" class="ti-form-control" required></div><div class="grid grid-cols-1 md:grid-cols-3 gap-4"><div><label class="form-label">Category</label><input v-model="form.category" class="ti-form-control" required></div><div><label class="form-label">Impact</label><select v-model="form.impact_level" class="ti-form-select"><option>low</option><option>medium</option><option>high</option></select></div><div><label class="form-label">Project</label><select v-model="form.project_id" class="ti-form-select"><option value="">General</option><option v-for="project in projects" :key="project.id" :value="project.id">{{ project.name }}</option></select></div></div><div><label class="form-label">Recommendation</label><textarea v-model="form.recommendation" class="ti-form-control" rows="5" required></textarea></div></div><div class="box-footer flex justify-end gap-2"><button type="button" class="ti-btn ti-btn-light" @click="showModal = false">Cancel</button><button class="ti-btn ti-btn-primary" :disabled="form.processing">Save Lesson</button></div></form></div></div>
</AppLayout></template>
